name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

#      - name: Analyze code
#        run: flutter analyze

#      - name: Run unit tests
#        run: flutter test

      - name: Build APK
        run: flutter build apk --debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v3
        with:
          name: debug-apk

      - name: Deploy to Firebase App Distribution
        env:
          FIREBASE_TOKEN: '1//0g1OmTS3kAH3nCgYIARAAGBASNwF-L9IrbyG_OcVf0mq8-g0qgjCZA2tldmoY5zyvGcwNHCWdNSZbH0js8iUrymzwgKMuV2o7uEo'
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute app-debug.apk \
            --app 1:301840111204:android:8d3ecaecdf7e5eb1a47171  \
            --groups testers

    # Additional deployment steps (e.g., deploying to Play Store) can be added here.
